/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-12-11 00:16:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>FoodWorld.com</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #F3F3F3;\">\r\n");
      out.write("<div class=\"container\" style=\"width:600px;\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 style=\"text-align: center; font-size:500%; padding-top:90px;font-family:verdana;text-shadow: 4px 2.5px #A8A8A8;\">FOOD WORLD</h1><br>\r\n");
      out.write("\t<p style=\"text-align: center; font-size:150%; font-weight: bold; \"> Connecting foodies</p><hr style=\"height:1px;background-color:#DDD;\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" style=\"width:500px;\">\r\n");
      out.write("<!-- <form action=\"/Reservation/loginAction\" method=\"post\">  -->\r\n");
      out.write("    <div style=\"padding-bottom:5px;\"><INPUT style=\"height: 1cm;font-size:17px\" TYPE=\"text\" id=\"userName\" placeholder=\"Enter username\" class=\"form-control\" maxlength=\"225\"/></div>\r\n");
      out.write("    <div style=\"padding-bottom:7px;\"><INPUT style=\"height: 1cm;font-size:17px\" TYPE=\"password\" id=\"password\" placeholder=\"Enter password\" class=\"form-control\" maxlength=\"225\"/></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("    <button class=\"btn btn-primary col-xs-1\" id=\"login\" style=\"width:227px;height: 1cm;font-size:18px\">Login</button>\r\n");
      out.write("    <div class=\"col-xs-1\">\r\n");
      out.write("      <button class=\"btn btn-primary btn-block\" style=\"width:226px;height: 1cm;font-size:18px\" onclick=\"location.href = '/Reservation/createaccount.jsp';\">Register</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("\r\n");
      out.write("   $(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#login\").click(loginHandler);\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("function loginHandler() {\r\n");
      out.write("\tvar username = $(\"#userName\").val();\r\n");
      out.write("\tvar password = $(\"#password\").val();\r\n");
      out.write("\tif ((username == \"\") && (password == \"\"))\r\n");
      out.write("\t\tlocation.href=\"/Reservation/login.jsp\";\r\n");
      out.write("\telse {\r\n");
      out.write("\tvar newLogin = {\r\n");
      out.write("\t\t\t\"userName\":username,\r\n");
      out.write("\t\t\t\"password\":password,\r\n");
      out.write("\t};\r\n");
      out.write("\thandleLogin(newLogin);\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function handleLogin(login) {\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"http://localhost:8080/Reservation/rest/user/login\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tdata : JSON.stringify(login),\r\n");
      out.write("\t\tdataType : \"text\",\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t//alert(response.status == \"pass\");\r\n");
      out.write("\t\t\t  if(response == \"pass\") location.href = \"/Reservation/home.jsp\";\r\n");
      out.write("\t\t\t\telse alert(\"Username/Password is incorrect\"); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" style=\"width:600px;\"><hr style=\"height:1px;background-color:#DDD;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
