/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-12-11 00:17:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.Person;
import rest.RestaurantSearch;
import java.util.ArrayList;
import java.util.List;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");

	Person person = (Person)session.getAttribute("user");
	if (person == null) {

      out.write("\r\n");
      out.write("<script>alert(\"Please login\");</script>\r\n");
      if (true) {
        _jspx_page_context.forward("/login.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');

	};

      out.write("\r\n");
      out.write("<title>Search</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body style= \"background-color:#F3F3F3;\">\r\n");
      out.write("\r\n");
      out.write("<div style= \"background-color: #006699;color:white;text-indent:20px;padding-top:5px;padding-bottom:5px;\">\r\n");
      out.write("  <span style=\"font-size:150%;font-weight: bold;\">Food World</span>\r\n");
      out.write("  <span style=\"float:right;padding-right:20px;padding-top:5px;\">\r\n");
      out.write("     <button id=\"logout\" class=\"btn btn-link btn-xs\" style=\"color:#FFF\">Logout</button>\r\n");
      out.write("  </span>\r\n");
      out.write("  <span style=\"float:right;padding-right:10px;padding-top:5px;font-weight: bold;font-size:12pt;\">\r\n");
      out.write("     <a href=\"/Reservation/home.jsp\" style=\"color:#FFF\">Home</a>\r\n");
      out.write("  </span>\r\n");
      out.write("  <span style=\"float:right;padding-right:20px;font-weight: bold;font-size:150%;\">\r\n");
      out.write("     <a href=\"/Reservation/profile.jsp\" style=\"color:#FFF\">");
      out.print( person.getFirstName() );
      out.write("</a>\r\n");
      out.write("  </span>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<div style= \"background-color: #83888E;padding-right:10px;padding-top:20px;padding-bottom:5px; width:200px; height:330px;float:left;\"> \r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;\"><a href=\"/Reservation/search.jsp\" style=\"color:#FFF\">Search restaurants</a></p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/home.jsp\" style=\"color:#FFF\"> My reservations</a> </p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/favorites.jsp\" style=\"color:#FFF\"> My favorites</a> </p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/reviews.jsp\" style=\"color:#FFF\"> My reviews</a> </p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/following.jsp\" style=\"color:#FFF\"> Following</a> </p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/finduser.jsp\" style=\"color:#FFF\"> Find a user</a> </p>\r\n");
      out.write("<p style=\"text-indent:20px;font-size:120%;font-weight: bold;padding-top:5px;\"> <a href=\"/Reservation/editprofile.jsp\" style=\"color:#FFF\"> Edit profile</a> </p>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"margin-left: 1.2cm;margin-top: 0.1cm;float: left; width:700px\">\r\n");
      out.write("<h1 style=\"font-size:300%;text-indent: 20px;float:left;\">Search a restaurant</h1>\r\n");
      out.write("\r\n");
      out.write("<hr style=\"height:1px;background-color:#DDD;clear:both\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"div1\" style=\"display:block;\">\r\n");
      out.write("\r\n");
      out.write("   <div style=\"margin-left: 0.2cm;\">\r\n");
      out.write("       <INPUT style=\"font-size:17px;height: 1cm;\" TYPE=\"text\" id=\"name\" placeholder=\"Restaurant name\" class=\"form-control\" maxlength=\"225\" style/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div style=\"margin-left: 0.2cm;margin-top: 0.2cm;\">\r\n");
      out.write("       <INPUT style=\"font-size:17px;height: 1cm;\" TYPE=\"text\" id=\"location\" placeholder=\"Location or place\" class=\"form-control\" maxlength=\"225\" style/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div style=\"margin-left: 0.2cm;margin-top: 0.3cm;\">\r\n");
      out.write("       <button id=\"search\" class=\"btn btn-primary btn-block\" style=\"height: 1cm;font-size:18px\" onclick = \"searchRestaurant()\">Search restaurant</button>\r\n");
      out.write("   </div>\r\n");
      out.write("\t  <hr style=\"height:1px;background-color:#DDD;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("\t$(\"#logout\").click(logoutHandler);\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function logoutHandler(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"http://localhost:8080/Reservation/rest/user/logout\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href= \"/Reservation/login.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchRestaurant() {\r\n");
      out.write("\t\tvar restaurantName = $(\"#name\").val();\r\n");
      out.write("\t\tvar location = $(\"#location\").val();\r\n");
      out.write("\t\tvar searchParameters = restaurantName+\",\"+location;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ((restaurantName == \"\") && (location == \"\")) {\r\n");
      out.write("\t\t\t//Do nothing\r\n");
      out.write("\t\t} else  {\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"http://localhost:8080/Reservation/rest/search/\"+searchParameters,\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tasync:false,\r\n");
      out.write("\t\t\tsuccess : responseHandler\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction responseHandler() {\r\n");
      out.write("\t\tlocation.href = \"/Reservation/searchresults.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
